# Generated by Django 3.2 on 2021-09-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='OutlookUser',
        ),
    ]
