# Generated by Django 3.2 on 2021-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_rename_user_outlookuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='No Title', max_length=264)),
                ('start_date', models.DateTimeField(default='no date')),
                ('end_date', models.DateTimeField(default='no date')),
            ],
        ),
    ]
