# Generated by Django 3.2.4 on 2021-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20211018_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
        ),
    ]
