# Generated by Django 3.2.4 on 2021-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_newevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
