# Generated by Django 3.2.4 on 2021-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('webmail', models.EmailField(max_length=254)),
                ('complaint', models.TextField()),
            ],
        ),
    ]
