# Generated by Django 3.0.7 on 2022-01-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('boardName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('position', models.CharField(max_length=40)),
                ('notices', models.TextField()),
                ('events', models.TextField()),
                ('announcements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('tag', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('mobile', models.CharField(max_length=20)),
                ('linked_in', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.Panel')),
            ],
        ),
    ]
