# Generated by Django 3.0.7 on 2022-01-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='position',
        ),
        migrations.AddField(
            model_name='board',
            name='chairman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.Senator'),
            preserve_default=False,
        ),
    ]
