# Generated by Django 3.0.7 on 2021-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='position',
            field=models.CharField(max_length=60),
        ),
    ]
