# Generated by Django 3.2.4 on 2021-07-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('aim', models.TextField()),
                ('activities', models.TextField()),
                ('acheivements', models.TextField()),
                ('pastEvents', models.TextField()),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.users')),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('icon', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.users')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.clubs')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.events')),
            ],
        ),
    ]
