# Generated by Django 3.2.4 on 2021-12-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.panel'),
        ),
    ]
