# Generated by Django 3.0.7 on 2022-02-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_board_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
