# Generated by Django 3.2.4 on 2022-01-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_gallery_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='position',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
