# Generated by Django 3.2.4 on 2022-01-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_senator_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GirlSenator',
        ),
        migrations.DeleteModel(
            name='PGSenator',
        ),
        migrations.DeleteModel(
            name='UGSenator',
        ),
        migrations.AddField(
            model_name='senator',
            name='tag',
            field=models.IntegerField(null=True),
        ),
    ]
