# Generated by Django 3.2.4 on 2022-01-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20220103_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='tag',
            field=models.IntegerField(help_text='0 for adosa,1 for senators,2 for UGs,3 for PGs,4 for Girls', null=True),
        ),
    ]
