# Generated by Django 3.0.7 on 2022-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20220110_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('boardName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('position', models.CharField(max_length=40)),
                ('notices', models.TextField()),
                ('events', models.TextField()),
                ('announcements', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
